//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALlyHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certification
    {
        public int CertificateID { get; set; }
        public string Name { get; set; }
        public int DeveloperID { get; set; }
        public string Provider { get; set; }
        public string CertificationLink { get; set; }
        public Nullable<System.DateTime> DateEarned { get; set; }
    
        public virtual Developer Developer { get; set; }
    }
}
