//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALlyHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeveloperSkill
    {
        public int SkillID { get; set; }
        public string SkillName { get; set; }
        public int DeveloperID { get; set; }
    
        public virtual Developer Developer { get; set; }
    }
}
