//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALlyHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Handshakes = new HashSet<Handshake>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectTitle { get; set; }
        public string Description { get; set; }
        public Nullable<int> PaymentAmount { get; set; }
        public int ClientID { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> Duration { get; set; }
        public string SkillSet { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Handshake> Handshakes { get; set; }
    }
}
